version: "3"

tasks:
    default:
        deps:
            - build

    build:
        cmds:
            - go build

    clean:
        cmds:
            - go clean

    format:
        cmds:
            - go fmt && goimports -w *.go

    lint:
        cmds:
            - golangci-lint run
    update:
        cmds:
            - go test -tags="all" -v -run TestIntegrationAddressBookQueryUpdateAll
    test:
        deps:
            - "test:unit"
            - "test:integration"

    "test:unit":
        cmds:
            - go test -tags="unit" -v

    "test:integration":
        cmds:
            - go test -tags="e2e" -v -timeout 9999s
    run-examples:
        cmds:
            - |
                for example in examples/*; do
                    if [ -d "$example" ]; then
                        pushd "$example" > /dev/null
                        if [ -f main.go ]; then
                            echo "Running $example/main.go"
                            go run main.go
                            if [ $? -ne 0 ]; then
                                echo "Error: $example/main.go failed"
                                exit 1
                            fi
                        fi
                        popd > /dev/null
                    fi
                done
