version: "3"

tasks:
    default:
        deps:
            - build

    build:
        cmds:
            - go build

    clean:
        cmds:
            - go clean

    format:
        cmds:
            - go fmt && goimports -w *.go

    lint:
        cmds:
            - golangci-lint run
    update:
        cmds:
            - go test -tags="all" -v -run TestIntegrationAddressBookQueryUpdateAll
    test:
        deps:
            - "test:unit"
            - "test:integration"

    "test:unit":
        cmds:
            - go test -tags="unit" -v

    "test:integration":
        cmds:
            - go test -tags="e2e" -v -timeout 9999s
    run-examples:
        cmds:
            - |
              for example in examples/*; do
                  if [ -d "$example" ]; then
                      # Skip the consensus_pub_sub_chunked directory
                      if [ "$example" == "examples/consensus_pub_sub_chunked" ]; then
                          continue
                      fi

                      pushd "$example" > /dev/null
                      if [ -f main.go ]; then
                          echo "Running $example/main.go"
                          env OPERATOR_KEY="302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137" OPERATOR_ID="0.0.2" HEDERA_NETWORK="localhost" go run main.go
                      fi
                      popd > /dev/null
                  fi
              done

