// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FileGetInfo.proto

package hedera_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get all of the information about a file, except for its contents. When a file expires, it no longer exists, and there will be no info about it, and the fileInfo field will be blank. If a transaction or smart contract deletes the file, but it has not yet expired, then the fileInfo field will be non-empty, the deleted field will be true, its size will be 0, and its contents will be empty. Note that each file has a FileID, but does not have a filename.
type FileGetInfoQuery struct {
	Header               *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FileID               *FileID      `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileGetInfoQuery) Reset()         { *m = FileGetInfoQuery{} }
func (m *FileGetInfoQuery) String() string { return proto.CompactTextString(m) }
func (*FileGetInfoQuery) ProtoMessage()    {}
func (*FileGetInfoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e334415d6856ea, []int{0}
}

func (m *FileGetInfoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileGetInfoQuery.Unmarshal(m, b)
}
func (m *FileGetInfoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileGetInfoQuery.Marshal(b, m, deterministic)
}
func (m *FileGetInfoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileGetInfoQuery.Merge(m, src)
}
func (m *FileGetInfoQuery) XXX_Size() int {
	return xxx_messageInfo_FileGetInfoQuery.Size(m)
}
func (m *FileGetInfoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FileGetInfoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FileGetInfoQuery proto.InternalMessageInfo

func (m *FileGetInfoQuery) GetHeader() *QueryHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FileGetInfoQuery) GetFileID() *FileID {
	if m != nil {
		return m.FileID
	}
	return nil
}

// Response when the client sends the node FileGetInfoQuery
type FileGetInfoResponse struct {
	Header               *ResponseHeader               `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FileInfo             *FileGetInfoResponse_FileInfo `protobuf:"bytes,2,opt,name=fileInfo,proto3" json:"fileInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FileGetInfoResponse) Reset()         { *m = FileGetInfoResponse{} }
func (m *FileGetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*FileGetInfoResponse) ProtoMessage()    {}
func (*FileGetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e334415d6856ea, []int{1}
}

func (m *FileGetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileGetInfoResponse.Unmarshal(m, b)
}
func (m *FileGetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileGetInfoResponse.Marshal(b, m, deterministic)
}
func (m *FileGetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileGetInfoResponse.Merge(m, src)
}
func (m *FileGetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_FileGetInfoResponse.Size(m)
}
func (m *FileGetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileGetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileGetInfoResponse proto.InternalMessageInfo

func (m *FileGetInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FileGetInfoResponse) GetFileInfo() *FileGetInfoResponse_FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

type FileGetInfoResponse_FileInfo struct {
	FileID               *FileID    `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	Size                 int64      `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ExpirationTime       *Timestamp `protobuf:"bytes,3,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	Deleted              bool       `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Keys                 *KeyList   `protobuf:"bytes,5,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileGetInfoResponse_FileInfo) Reset()         { *m = FileGetInfoResponse_FileInfo{} }
func (m *FileGetInfoResponse_FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileGetInfoResponse_FileInfo) ProtoMessage()    {}
func (*FileGetInfoResponse_FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_63e334415d6856ea, []int{1, 0}
}

func (m *FileGetInfoResponse_FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileGetInfoResponse_FileInfo.Unmarshal(m, b)
}
func (m *FileGetInfoResponse_FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileGetInfoResponse_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileGetInfoResponse_FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileGetInfoResponse_FileInfo.Merge(m, src)
}
func (m *FileGetInfoResponse_FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileGetInfoResponse_FileInfo.Size(m)
}
func (m *FileGetInfoResponse_FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileGetInfoResponse_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileGetInfoResponse_FileInfo proto.InternalMessageInfo

func (m *FileGetInfoResponse_FileInfo) GetFileID() *FileID {
	if m != nil {
		return m.FileID
	}
	return nil
}

func (m *FileGetInfoResponse_FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileGetInfoResponse_FileInfo) GetExpirationTime() *Timestamp {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

func (m *FileGetInfoResponse_FileInfo) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *FileGetInfoResponse_FileInfo) GetKeys() *KeyList {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*FileGetInfoQuery)(nil), "proto.FileGetInfoQuery")
	proto.RegisterType((*FileGetInfoResponse)(nil), "proto.FileGetInfoResponse")
	proto.RegisterType((*FileGetInfoResponse_FileInfo)(nil), "proto.FileGetInfoResponse.FileInfo")
}

func init() { proto.RegisterFile("FileGetInfo.proto", fileDescriptor_63e334415d6856ea) }

var fileDescriptor_63e334415d6856ea = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0x7f, 0x7d, 0xcb, 0x7c, 0xb5, 0xb6, 0xab, 0x42, 0xe8, 0xa9, 0x44, 0x84, 0x22,
	0x98, 0x83, 0x7a, 0xf0, 0x26, 0x14, 0xa9, 0x16, 0x3d, 0xe8, 0xd2, 0x93, 0x17, 0x59, 0x9b, 0xa9,
	0x59, 0x6d, 0xb3, 0x4b, 0x76, 0x15, 0xe3, 0xff, 0xe6, 0xd1, 0xff, 0x4b, 0x3a, 0xd9, 0x96, 0x35,
	0x07, 0x4f, 0x9b, 0xbc, 0xf9, 0xcc, 0x7b, 0x0f, 0x06, 0x7a, 0x63, 0xb9, 0xc0, 0x2b, 0xb4, 0x93,
	0x6c, 0xae, 0x62, 0x9d, 0x2b, 0xab, 0x58, 0x93, 0x9e, 0xfe, 0xce, 0x54, 0x2e, 0xd1, 0x58, 0xb1,
	0xd4, 0xa5, 0xde, 0xef, 0x8e, 0x84, 0x91, 0xb3, 0x69, 0xa1, 0xd1, 0x38, 0xa5, 0x77, 0xff, 0x86,
	0x79, 0x71, 0x8d, 0x22, 0xc1, 0xdc, 0x49, 0x7b, 0x1c, 0x8d, 0x56, 0x99, 0x41, 0x5f, 0x8d, 0x10,
	0xba, 0x5e, 0x0e, 0x6d, 0xb1, 0x23, 0x68, 0xa5, 0xc4, 0x84, 0xc1, 0x20, 0x18, 0xfe, 0x3f, 0x61,
	0x25, 0x1b, 0x7b, 0x9e, 0xdc, 0x11, 0xec, 0x10, 0x5a, 0x73, 0xb9, 0xc0, 0xc9, 0x65, 0x58, 0x23,
	0x76, 0xdb, 0xb1, 0x63, 0x12, 0xb9, 0x1b, 0x46, 0xdf, 0x35, 0xd8, 0xf5, 0x72, 0xd6, 0x55, 0xd8,
	0x71, 0x25, 0x6a, 0xdf, 0xad, 0xff, 0xee, 0xba, 0x49, 0xbb, 0x80, 0x36, 0x19, 0x66, 0x73, 0xe5,
	0xf2, 0x0e, 0xbc, 0xbc, 0x8a, 0x79, 0xd9, 0x61, 0x25, 0x6c, 0x96, 0xfa, 0x5f, 0x01, 0xb4, 0xd7,
	0xb2, 0xd7, 0x3d, 0xf8, 0xa3, 0x3b, 0x63, 0xd0, 0x30, 0xf2, 0x13, 0x29, 0xb0, 0xce, 0xe9, 0x9b,
	0x9d, 0x43, 0x07, 0x3f, 0xb4, 0xcc, 0x85, 0x95, 0x2a, 0x5b, 0x9d, 0x23, 0xac, 0x93, 0x45, 0xd7,
	0x59, 0x6c, 0x2e, 0xc4, 0x2b, 0x1c, 0x0b, 0xe1, 0x5f, 0x82, 0x0b, 0xb4, 0x98, 0x84, 0x8d, 0x41,
	0x30, 0x6c, 0xf3, 0xf5, 0x2f, 0x8b, 0xa0, 0xf1, 0x8a, 0x85, 0x09, 0x9b, 0xe4, 0xd4, 0x71, 0x4e,
	0x37, 0x58, 0xdc, 0x4a, 0x63, 0x39, 0xcd, 0x46, 0x67, 0x10, 0xcd, 0xd4, 0x32, 0x4e, 0x31, 0xc1,
	0x5c, 0xa4, 0xc2, 0xa4, 0xcf, 0xb9, 0xd0, 0x69, 0x2c, 0xb4, 0x74, 0xf8, 0x8b, 0x78, 0x17, 0x77,
	0xc1, 0xc3, 0x56, 0x49, 0x3c, 0x92, 0xf8, 0xd4, 0xa2, 0xe7, 0xf4, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xd8, 0x74, 0x9c, 0x53, 0x02, 0x00, 0x00,
}
