// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SystemDelete.proto

package hedera_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Delete a file or smart contract - can only be done with a Hedera admin multisig. When it is deleted, it immediately disappears from the system as seen by the user, but is still stored internally until the expiration time, at which time it is truly and permanently deleted. Until that time, it can be undeleted by the Hedera admin multisig. When a smart contract is deleted, the cryptocurrency account within it continues to exist, and is not affected by the expiration time here.
type SystemDeleteTransactionBody struct {
	// Types that are valid to be assigned to Id:
	//	*SystemDeleteTransactionBody_FileID
	//	*SystemDeleteTransactionBody_ContractID
	Id                   isSystemDeleteTransactionBody_Id `protobuf_oneof:"id"`
	ExpirationTime       *TimestampSeconds                `protobuf:"bytes,3,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SystemDeleteTransactionBody) Reset()         { *m = SystemDeleteTransactionBody{} }
func (m *SystemDeleteTransactionBody) String() string { return proto.CompactTextString(m) }
func (*SystemDeleteTransactionBody) ProtoMessage()    {}
func (*SystemDeleteTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_860c88b39ffc5dcc, []int{0}
}

func (m *SystemDeleteTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemDeleteTransactionBody.Unmarshal(m, b)
}
func (m *SystemDeleteTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemDeleteTransactionBody.Marshal(b, m, deterministic)
}
func (m *SystemDeleteTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemDeleteTransactionBody.Merge(m, src)
}
func (m *SystemDeleteTransactionBody) XXX_Size() int {
	return xxx_messageInfo_SystemDeleteTransactionBody.Size(m)
}
func (m *SystemDeleteTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemDeleteTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_SystemDeleteTransactionBody proto.InternalMessageInfo

type isSystemDeleteTransactionBody_Id interface {
	isSystemDeleteTransactionBody_Id()
}

type SystemDeleteTransactionBody_FileID struct {
	FileID *FileID `protobuf:"bytes,1,opt,name=fileID,proto3,oneof"`
}

type SystemDeleteTransactionBody_ContractID struct {
	ContractID *ContractID `protobuf:"bytes,2,opt,name=contractID,proto3,oneof"`
}

func (*SystemDeleteTransactionBody_FileID) isSystemDeleteTransactionBody_Id() {}

func (*SystemDeleteTransactionBody_ContractID) isSystemDeleteTransactionBody_Id() {}

func (m *SystemDeleteTransactionBody) GetId() isSystemDeleteTransactionBody_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SystemDeleteTransactionBody) GetFileID() *FileID {
	if x, ok := m.GetId().(*SystemDeleteTransactionBody_FileID); ok {
		return x.FileID
	}
	return nil
}

func (m *SystemDeleteTransactionBody) GetContractID() *ContractID {
	if x, ok := m.GetId().(*SystemDeleteTransactionBody_ContractID); ok {
		return x.ContractID
	}
	return nil
}

func (m *SystemDeleteTransactionBody) GetExpirationTime() *TimestampSeconds {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SystemDeleteTransactionBody) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SystemDeleteTransactionBody_FileID)(nil),
		(*SystemDeleteTransactionBody_ContractID)(nil),
	}
}

func init() {
	proto.RegisterType((*SystemDeleteTransactionBody)(nil), "proto.SystemDeleteTransactionBody")
}

func init() { proto.RegisterFile("SystemDelete.proto", fileDescriptor_860c88b39ffc5dcc) }

var fileDescriptor_860c88b39ffc5dcc = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x9b, 0x02, 0x1d, 0x8e, 0xff, 0x5e, 0x88, 0xca, 0x82, 0xba, 0xc0, 0x94, 0x81, 0xb2,
	0x23, 0x85, 0x08, 0xb5, 0x1b, 0x4a, 0x33, 0xb1, 0xa0, 0xc3, 0x39, 0xb0, 0x51, 0xfd, 0x47, 0xb6,
	0x85, 0xc8, 0xd7, 0xe3, 0x93, 0xa1, 0xda, 0x56, 0x15, 0x31, 0x9d, 0xf4, 0xde, 0xef, 0xbd, 0x7b,
	0xc0, 0x36, 0x83, 0x0f, 0xa4, 0x1a, 0xda, 0x52, 0xa0, 0xca, 0x3a, 0x13, 0x0c, 0x3b, 0x8a, 0x67,
	0x7e, 0x51, 0xa3, 0x97, 0xbc, 0x1b, 0x2c, 0xf9, 0x64, 0xcc, 0xcf, 0x3b, 0xa9, 0xc8, 0x07, 0x54,
	0x36, 0x09, 0x8b, 0xdf, 0x02, 0xae, 0xc7, 0x05, 0x9d, 0x43, 0xed, 0x91, 0x07, 0x69, 0x74, 0x6d,
	0xfa, 0x81, 0xdd, 0xc2, 0xec, 0x43, 0x6e, 0x69, 0xdd, 0x94, 0xc5, 0x4d, 0x71, 0x77, 0x7c, 0x7f,
	0x9a, 0x72, 0xd5, 0x73, 0x14, 0x57, 0x93, 0x36, 0xdb, 0x6c, 0x09, 0xc0, 0x8d, 0x0e, 0x0e, 0x79,
	0x58, 0x37, 0xe5, 0x34, 0xc2, 0x97, 0x19, 0x7e, 0xda, 0x1b, 0xab, 0x49, 0x3b, 0xc2, 0xd8, 0x23,
	0x9c, 0xd1, 0x8f, 0x95, 0x0e, 0x77, 0xff, 0x76, 0xd3, 0xca, 0x83, 0x18, 0xbc, 0xca, 0xc1, 0xfd,
	0xda, 0x0d, 0x71, 0xa3, 0x7b, 0xdf, 0xfe, 0xc3, 0xeb, 0x43, 0x98, 0xca, 0xbe, 0x7e, 0x80, 0x05,
	0x37, 0xaa, 0x12, 0xd4, 0x93, 0x43, 0x81, 0x5e, 0x7c, 0x3a, 0xb4, 0xa2, 0x42, 0x2b, 0x73, 0xcf,
	0x17, 0x7e, 0xe3, 0x4b, 0xf1, 0x7a, 0x92, 0x88, 0xb7, 0x28, 0xbe, 0xcf, 0xe2, 0x59, 0xfe, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xc1, 0x6b, 0x21, 0x2f, 0x41, 0x01, 0x00, 0x00,
}
