// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ContractGetInfo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get information about a smart contract instance. This includes the account that it uses, the file containing its bytecode, and the time when it will expire.
type ContractGetInfoQuery struct {
	Header               *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ContractID           *ContractID  `protobuf:"bytes,2,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContractGetInfoQuery) Reset()         { *m = ContractGetInfoQuery{} }
func (m *ContractGetInfoQuery) String() string { return proto.CompactTextString(m) }
func (*ContractGetInfoQuery) ProtoMessage()    {}
func (*ContractGetInfoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a717a6a53e417d6, []int{0}
}

func (m *ContractGetInfoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractGetInfoQuery.Unmarshal(m, b)
}
func (m *ContractGetInfoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractGetInfoQuery.Marshal(b, m, deterministic)
}
func (m *ContractGetInfoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractGetInfoQuery.Merge(m, src)
}
func (m *ContractGetInfoQuery) XXX_Size() int {
	return xxx_messageInfo_ContractGetInfoQuery.Size(m)
}
func (m *ContractGetInfoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractGetInfoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ContractGetInfoQuery proto.InternalMessageInfo

func (m *ContractGetInfoQuery) GetHeader() *QueryHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ContractGetInfoQuery) GetContractID() *ContractID {
	if m != nil {
		return m.ContractID
	}
	return nil
}

// Response when the client sends the node ContractGetInfoQuery
type ContractGetInfoResponse struct {
	Header               *ResponseHeader                       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ContractInfo         *ContractGetInfoResponse_ContractInfo `protobuf:"bytes,2,opt,name=contractInfo,proto3" json:"contractInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ContractGetInfoResponse) Reset()         { *m = ContractGetInfoResponse{} }
func (m *ContractGetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ContractGetInfoResponse) ProtoMessage()    {}
func (*ContractGetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a717a6a53e417d6, []int{1}
}

func (m *ContractGetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractGetInfoResponse.Unmarshal(m, b)
}
func (m *ContractGetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractGetInfoResponse.Marshal(b, m, deterministic)
}
func (m *ContractGetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractGetInfoResponse.Merge(m, src)
}
func (m *ContractGetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ContractGetInfoResponse.Size(m)
}
func (m *ContractGetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractGetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContractGetInfoResponse proto.InternalMessageInfo

func (m *ContractGetInfoResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ContractGetInfoResponse) GetContractInfo() *ContractGetInfoResponse_ContractInfo {
	if m != nil {
		return m.ContractInfo
	}
	return nil
}

type ContractGetInfoResponse_ContractInfo struct {
	ContractID           *ContractID `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	AccountID            *AccountID  `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	ContractAccountID    string      `protobuf:"bytes,3,opt,name=contractAccountID,proto3" json:"contractAccountID,omitempty"`
	AdminKey             *Key        `protobuf:"bytes,4,opt,name=adminKey,proto3" json:"adminKey,omitempty"`
	ExpirationTime       *Timestamp  `protobuf:"bytes,5,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	AutoRenewPeriod      *Duration   `protobuf:"bytes,6,opt,name=autoRenewPeriod,proto3" json:"autoRenewPeriod,omitempty"`
	Storage              int64       `protobuf:"varint,7,opt,name=storage,proto3" json:"storage,omitempty"`
	Memo                 string      `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractGetInfoResponse_ContractInfo) Reset()         { *m = ContractGetInfoResponse_ContractInfo{} }
func (m *ContractGetInfoResponse_ContractInfo) String() string { return proto.CompactTextString(m) }
func (*ContractGetInfoResponse_ContractInfo) ProtoMessage()    {}
func (*ContractGetInfoResponse_ContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a717a6a53e417d6, []int{1, 0}
}

func (m *ContractGetInfoResponse_ContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractGetInfoResponse_ContractInfo.Unmarshal(m, b)
}
func (m *ContractGetInfoResponse_ContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractGetInfoResponse_ContractInfo.Marshal(b, m, deterministic)
}
func (m *ContractGetInfoResponse_ContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractGetInfoResponse_ContractInfo.Merge(m, src)
}
func (m *ContractGetInfoResponse_ContractInfo) XXX_Size() int {
	return xxx_messageInfo_ContractGetInfoResponse_ContractInfo.Size(m)
}
func (m *ContractGetInfoResponse_ContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractGetInfoResponse_ContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContractGetInfoResponse_ContractInfo proto.InternalMessageInfo

func (m *ContractGetInfoResponse_ContractInfo) GetContractID() *ContractID {
	if m != nil {
		return m.ContractID
	}
	return nil
}

func (m *ContractGetInfoResponse_ContractInfo) GetAccountID() *AccountID {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *ContractGetInfoResponse_ContractInfo) GetContractAccountID() string {
	if m != nil {
		return m.ContractAccountID
	}
	return ""
}

func (m *ContractGetInfoResponse_ContractInfo) GetAdminKey() *Key {
	if m != nil {
		return m.AdminKey
	}
	return nil
}

func (m *ContractGetInfoResponse_ContractInfo) GetExpirationTime() *Timestamp {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

func (m *ContractGetInfoResponse_ContractInfo) GetAutoRenewPeriod() *Duration {
	if m != nil {
		return m.AutoRenewPeriod
	}
	return nil
}

func (m *ContractGetInfoResponse_ContractInfo) GetStorage() int64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *ContractGetInfoResponse_ContractInfo) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractGetInfoQuery)(nil), "proto.ContractGetInfoQuery")
	proto.RegisterType((*ContractGetInfoResponse)(nil), "proto.ContractGetInfoResponse")
	proto.RegisterType((*ContractGetInfoResponse_ContractInfo)(nil), "proto.ContractGetInfoResponse.ContractInfo")
}

func init() { proto.RegisterFile("proto/ContractGetInfo.proto", fileDescriptor_8a717a6a53e417d6) }

var fileDescriptor_8a717a6a53e417d6 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6f, 0xd4, 0x30,
	0x10, 0x85, 0x95, 0x76, 0xbb, 0x6d, 0x87, 0x8a, 0x52, 0xab, 0xa5, 0x56, 0xb8, 0xac, 0x7a, 0x40,
	0x11, 0xb0, 0x89, 0x80, 0x0b, 0x1c, 0x69, 0x2b, 0xd1, 0xaa, 0x07, 0x8a, 0xd5, 0x13, 0x37, 0x37,
	0x99, 0x4d, 0x22, 0x14, 0x3b, 0xb2, 0x1d, 0x41, 0xfe, 0x00, 0x3f, 0x96, 0x5f, 0x81, 0xd6, 0x76,
	0xb2, 0x59, 0x73, 0xe9, 0xc9, 0xbb, 0xef, 0x7d, 0xf3, 0xde, 0x38, 0x32, 0xbc, 0x6a, 0x95, 0x34,
	0x32, 0xbb, 0x92, 0xc2, 0x28, 0x9e, 0x9b, 0xaf, 0x68, 0x6e, 0xc5, 0x4a, 0xa6, 0x56, 0x25, 0x7b,
	0xf6, 0x88, 0xcf, 0x1c, 0xf3, 0x50, 0x37, 0xa8, 0x0d, 0x6f, 0x5a, 0xe7, 0xc6, 0xa7, 0x4e, 0xbe,
	0xee, 0x14, 0x37, 0xb5, 0x14, 0x5e, 0x7d, 0xe9, 0xd4, 0x4b, 0xae, 0xeb, 0xfc, 0xa1, 0x6f, 0x51,
	0x7b, 0xfd, 0xdc, 0xe9, 0xdf, 0x3b, 0x54, 0xfd, 0x0d, 0xf2, 0x02, 0x95, 0x37, 0x62, 0x67, 0x30,
	0xd4, 0xad, 0x14, 0x1a, 0xa7, 0xde, 0x45, 0x07, 0xa7, 0xc1, 0x66, 0x76, 0x9e, 0xbc, 0x81, 0x79,
	0x65, 0x39, 0x1a, 0x2d, 0xa2, 0xe4, 0xd9, 0x07, 0xe2, 0xf8, 0x74, 0x92, 0xce, 0x3c, 0x41, 0xde,
	0x03, 0xe4, 0x3e, 0xe3, 0xf6, 0x9a, 0xee, 0x58, 0xfe, 0xc4, 0xf3, 0x57, 0xa3, 0xc1, 0x26, 0xd0,
	0xc5, 0x9f, 0x19, 0x9c, 0x07, 0xbd, 0xc3, 0x7a, 0x64, 0x19, 0x54, 0x9f, 0xf9, 0xa8, 0xed, 0xfd,
	0xc7, 0xf6, 0x6f, 0x70, 0x34, 0x06, 0x8b, 0x95, 0xf4, 0xfd, 0x6f, 0x83, 0xfe, 0xa0, 0x64, 0xb3,
	0xd7, 0x5a, 0xdc, 0x0a, 0x88, 0xff, 0xee, 0xc0, 0xd1, 0xd4, 0x0e, 0xee, 0x17, 0x3d, 0xe1, 0x7e,
	0x24, 0x85, 0x43, 0x9e, 0xe7, 0xb2, 0x13, 0x9b, 0x2f, 0xf2, 0xc2, 0x4f, 0x7c, 0x19, 0x74, 0xb6,
	0x41, 0xc8, 0x3b, 0x38, 0x19, 0xa6, 0x47, 0x9f, 0xee, 0x2e, 0xa2, 0xe4, 0x90, 0xfd, 0x6f, 0x90,
	0xd7, 0x70, 0xc0, 0x8b, 0xa6, 0x16, 0x77, 0xd8, 0xd3, 0x99, 0x0d, 0x07, 0x1f, 0x7e, 0x87, 0x3d,
	0x1b, 0x3d, 0xf2, 0x09, 0x9e, 0xe3, 0xef, 0xb6, 0x76, 0xaf, 0x67, 0xfd, 0xb8, 0xe8, 0xde, 0xd6,
	0x2a, 0xe3, 0x7b, 0x63, 0x01, 0x47, 0x3e, 0xc3, 0x31, 0xef, 0x8c, 0x64, 0x28, 0xf0, 0xd7, 0x3d,
	0xaa, 0x5a, 0x16, 0x74, 0x6e, 0x47, 0x8f, 0xfd, 0xe8, 0xf0, 0x26, 0x59, 0xc8, 0x11, 0x0a, 0xfb,
	0xda, 0x48, 0xc5, 0x4b, 0xa4, 0xfb, 0x8b, 0x28, 0xd9, 0x65, 0xc3, 0x5f, 0x42, 0x60, 0xd6, 0x60,
	0x23, 0xe9, 0x81, 0xbd, 0x97, 0xfd, 0x7d, 0x79, 0x03, 0x71, 0x2e, 0x9b, 0xb4, 0xc2, 0x02, 0x15,
	0x4f, 0x2b, 0xae, 0xab, 0x52, 0xf1, 0xb6, 0x72, 0x2d, 0xf7, 0xd1, 0x8f, 0xa4, 0xac, 0x4d, 0xd5,
	0x3d, 0xa6, 0xb9, 0x6c, 0xb2, 0xd1, 0xcd, 0x1c, 0xbe, 0xd4, 0xc5, 0xcf, 0x65, 0x29, 0x33, 0xcb,
	0x3e, 0xce, 0xed, 0xf1, 0xf1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x48, 0x12, 0xd9, 0x70,
	0x03, 0x00, 0x00,
}
