// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ContractCall.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Call a function of the given smart contract instance, giving it functionParameters as its inputs. it can use the given amount of gas, and any unspent gas will be refunded to the paying account.
//
// If this function stores information, it is charged gas to store it. There is a fee in hbars to maintain that storage until the expiration time, and that fee is added as part of the transaction fee.
type ContractCallTransactionBody struct {
	ContractID           *ContractID `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Gas                  int64       `protobuf:"varint,2,opt,name=gas,proto3" json:"gas,omitempty"`
	Amount               int64       `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	FunctionParameters   []byte      `protobuf:"bytes,4,opt,name=functionParameters,proto3" json:"functionParameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractCallTransactionBody) Reset()         { *m = ContractCallTransactionBody{} }
func (m *ContractCallTransactionBody) String() string { return proto.CompactTextString(m) }
func (*ContractCallTransactionBody) ProtoMessage()    {}
func (*ContractCallTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd9f6f84c001af30, []int{0}
}

func (m *ContractCallTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractCallTransactionBody.Unmarshal(m, b)
}
func (m *ContractCallTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractCallTransactionBody.Marshal(b, m, deterministic)
}
func (m *ContractCallTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractCallTransactionBody.Merge(m, src)
}
func (m *ContractCallTransactionBody) XXX_Size() int {
	return xxx_messageInfo_ContractCallTransactionBody.Size(m)
}
func (m *ContractCallTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractCallTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_ContractCallTransactionBody proto.InternalMessageInfo

func (m *ContractCallTransactionBody) GetContractID() *ContractID {
	if m != nil {
		return m.ContractID
	}
	return nil
}

func (m *ContractCallTransactionBody) GetGas() int64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *ContractCallTransactionBody) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ContractCallTransactionBody) GetFunctionParameters() []byte {
	if m != nil {
		return m.FunctionParameters
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractCallTransactionBody)(nil), "proto.ContractCallTransactionBody")
}

func init() { proto.RegisterFile("ContractCall.proto", fileDescriptor_bd9f6f84c001af30) }

var fileDescriptor_bd9f6f84c001af30 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4e, 0x85, 0x30,
	0x10, 0x86, 0x53, 0x51, 0x16, 0xa3, 0x0b, 0xec, 0xc2, 0x34, 0xba, 0x21, 0x2c, 0x0c, 0xab, 0x26,
	0xea, 0x0d, 0xc0, 0x8d, 0x3b, 0x42, 0xb8, 0xc0, 0x58, 0x2a, 0xc5, 0x40, 0xdb, 0xb4, 0xc5, 0x84,
	0x2b, 0x79, 0xca, 0x97, 0x57, 0xc8, 0x0b, 0x8b, 0xb7, 0x9a, 0xf9, 0xe7, 0xfb, 0x26, 0x33, 0x40,
	0x6b, 0xa3, 0x83, 0x43, 0x11, 0x6a, 0x9c, 0x26, 0x6e, 0x9d, 0x09, 0x86, 0xde, 0xc5, 0xf2, 0x9c,
	0x55, 0xe8, 0x47, 0xd1, 0xad, 0x56, 0xfa, 0x0d, 0x14, 0xff, 0x04, 0x5e, 0x8e, 0x7e, 0xe7, 0x50,
	0x7b, 0x14, 0x61, 0x34, 0xba, 0x32, 0xfd, 0x4a, 0xdf, 0x00, 0xc4, 0x8e, 0xbf, 0x3e, 0x19, 0xc9,
	0x49, 0x79, 0xff, 0xfe, 0xb8, 0xed, 0xf2, 0xfa, 0x02, 0xda, 0x83, 0x44, 0x33, 0x48, 0x06, 0xf4,
	0xec, 0x26, 0x27, 0x65, 0xd2, 0x9e, 0x5b, 0xfa, 0x04, 0x29, 0xce, 0x66, 0xd1, 0x81, 0x25, 0x71,
	0xb8, 0x27, 0xca, 0x81, 0xfe, 0x2c, 0x3a, 0x1e, 0x6b, 0xd0, 0xe1, 0x2c, 0x83, 0x74, 0x9e, 0xdd,
	0xe6, 0xa4, 0x7c, 0x68, 0xaf, 0x90, 0xea, 0x15, 0x0a, 0x61, 0x66, 0xae, 0x64, 0x2f, 0x1d, 0x2a,
	0xf4, 0x6a, 0x70, 0x68, 0x15, 0x47, 0x3b, 0xee, 0x1f, 0xfd, 0xe2, 0x1f, 0x36, 0xe4, 0x3b, 0x8d,
	0xe9, 0xe3, 0x14, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x49, 0x35, 0xd6, 0x0a, 0x01, 0x00, 0x00,
}
