// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/CryptoDeleteClaim.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Delete a claim hash that was attached to the given account. This transaction is valid if signed by all the keys used for transfers out of the account. It is also valid if signed by any single ThresholdKeys in the deleteKeys list for this hash. See CryptoAddClaimTransaction for more information about claim hashes.
type CryptoDeleteClaimTransactionBody struct {
	AccountIDToDeleteFrom *AccountID `protobuf:"bytes,1,opt,name=accountIDToDeleteFrom,proto3" json:"accountIDToDeleteFrom,omitempty"`
	HashToDelete          []byte     `protobuf:"bytes,2,opt,name=hashToDelete,proto3" json:"hashToDelete,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *CryptoDeleteClaimTransactionBody) Reset()         { *m = CryptoDeleteClaimTransactionBody{} }
func (m *CryptoDeleteClaimTransactionBody) String() string { return proto.CompactTextString(m) }
func (*CryptoDeleteClaimTransactionBody) ProtoMessage()    {}
func (*CryptoDeleteClaimTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d398845b901a042, []int{0}
}

func (m *CryptoDeleteClaimTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoDeleteClaimTransactionBody.Unmarshal(m, b)
}
func (m *CryptoDeleteClaimTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoDeleteClaimTransactionBody.Marshal(b, m, deterministic)
}
func (m *CryptoDeleteClaimTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoDeleteClaimTransactionBody.Merge(m, src)
}
func (m *CryptoDeleteClaimTransactionBody) XXX_Size() int {
	return xxx_messageInfo_CryptoDeleteClaimTransactionBody.Size(m)
}
func (m *CryptoDeleteClaimTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoDeleteClaimTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoDeleteClaimTransactionBody proto.InternalMessageInfo

func (m *CryptoDeleteClaimTransactionBody) GetAccountIDToDeleteFrom() *AccountID {
	if m != nil {
		return m.AccountIDToDeleteFrom
	}
	return nil
}

func (m *CryptoDeleteClaimTransactionBody) GetHashToDelete() []byte {
	if m != nil {
		return m.HashToDelete
	}
	return nil
}

func init() {
	proto.RegisterType((*CryptoDeleteClaimTransactionBody)(nil), "proto.CryptoDeleteClaimTransactionBody")
}

func init() { proto.RegisterFile("proto/CryptoDeleteClaim.proto", fileDescriptor_6d398845b901a042) }

var fileDescriptor_6d398845b901a042 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0x77, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0x75, 0xce,
	0x49, 0xcc, 0xcc, 0xd5, 0x03, 0x8b, 0x0b, 0xb1, 0x82, 0x29, 0x29, 0x31, 0x88, 0x2a, 0xa7, 0xc4,
	0xe2, 0xcc, 0xe4, 0x90, 0xca, 0x82, 0xd4, 0x62, 0x88, 0xb4, 0x52, 0x1f, 0x23, 0x97, 0x02, 0x86,
	0xd6, 0x90, 0xa2, 0xc4, 0xbc, 0xe2, 0xc4, 0xe4, 0x92, 0xcc, 0xfc, 0x3c, 0xa7, 0xfc, 0x94, 0x4a,
	0x21, 0x37, 0x2e, 0xd1, 0xc4, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc, 0x12, 0x4f, 0x97, 0x10, 0xa8, 0x42,
	0xb7, 0xa2, 0xfc, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x01, 0x88, 0x59, 0x7a, 0x8e,
	0x30, 0x35, 0x41, 0xd8, 0x95, 0x0b, 0x29, 0x71, 0xf1, 0x64, 0x24, 0x16, 0x67, 0xc0, 0xc4, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x50, 0xc4, 0x9c, 0x3c, 0xb8, 0xa4, 0x92, 0xf3, 0x73, 0xf5,
	0x32, 0x52, 0x53, 0x52, 0x8b, 0x12, 0xf5, 0x40, 0x52, 0xe9, 0x45, 0x89, 0x05, 0x19, 0x10, 0x2b,
	0x02, 0x18, 0xa3, 0x34, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xe1,
	0xb2, 0xfa, 0x10, 0xe5, 0xba, 0xc5, 0x29, 0xd9, 0xba, 0xe9, 0xf9, 0xfa, 0x60, 0xb5, 0x49, 0x6c,
	0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x07, 0xef, 0xc8, 0x21, 0x01, 0x00, 0x00,
}
