// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Response.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A single response, which is returned from the node to the client, after the client sent the node a query. This includes all responses.
type Response struct {
	// Types that are valid to be assigned to Response:
	//	*Response_GetByKey
	//	*Response_GetBySolidityID
	//	*Response_ContractCallLocal
	//	*Response_ContractGetBytecodeResponse
	//	*Response_ContractGetInfo
	//	*Response_ContractGetRecordsResponse
	//	*Response_CryptogetAccountBalance
	//	*Response_CryptoGetAccountRecords
	//	*Response_CryptoGetInfo
	//	*Response_CryptoGetClaim
	//	*Response_CryptoGetProxyStakers
	//	*Response_FileGetContents
	//	*Response_FileGetInfo
	//	*Response_TransactionGetReceipt
	//	*Response_TransactionGetRecord
	//	*Response_TransactionGetFastRecord
	Response             isResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c4c7055b2f7bc3f, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Response interface {
	isResponse_Response()
}

type Response_GetByKey struct {
	GetByKey *GetByKeyResponse `protobuf:"bytes,1,opt,name=getByKey,proto3,oneof"`
}

type Response_GetBySolidityID struct {
	GetBySolidityID *GetBySolidityIDResponse `protobuf:"bytes,2,opt,name=getBySolidityID,proto3,oneof"`
}

type Response_ContractCallLocal struct {
	ContractCallLocal *ContractCallLocalResponse `protobuf:"bytes,3,opt,name=contractCallLocal,proto3,oneof"`
}

type Response_ContractGetBytecodeResponse struct {
	ContractGetBytecodeResponse *ContractGetBytecodeResponse `protobuf:"bytes,5,opt,name=contractGetBytecodeResponse,proto3,oneof"`
}

type Response_ContractGetInfo struct {
	ContractGetInfo *ContractGetInfoResponse `protobuf:"bytes,4,opt,name=contractGetInfo,proto3,oneof"`
}

type Response_ContractGetRecordsResponse struct {
	ContractGetRecordsResponse *ContractGetRecordsResponse `protobuf:"bytes,6,opt,name=contractGetRecordsResponse,proto3,oneof"`
}

type Response_CryptogetAccountBalance struct {
	CryptogetAccountBalance *CryptoGetAccountBalanceResponse `protobuf:"bytes,7,opt,name=cryptogetAccountBalance,proto3,oneof"`
}

type Response_CryptoGetAccountRecords struct {
	CryptoGetAccountRecords *CryptoGetAccountRecordsResponse `protobuf:"bytes,8,opt,name=cryptoGetAccountRecords,proto3,oneof"`
}

type Response_CryptoGetInfo struct {
	CryptoGetInfo *CryptoGetInfoResponse `protobuf:"bytes,9,opt,name=cryptoGetInfo,proto3,oneof"`
}

type Response_CryptoGetClaim struct {
	CryptoGetClaim *CryptoGetClaimResponse `protobuf:"bytes,10,opt,name=cryptoGetClaim,proto3,oneof"`
}

type Response_CryptoGetProxyStakers struct {
	CryptoGetProxyStakers *CryptoGetStakersResponse `protobuf:"bytes,11,opt,name=cryptoGetProxyStakers,proto3,oneof"`
}

type Response_FileGetContents struct {
	FileGetContents *FileGetContentsResponse `protobuf:"bytes,12,opt,name=fileGetContents,proto3,oneof"`
}

type Response_FileGetInfo struct {
	FileGetInfo *FileGetInfoResponse `protobuf:"bytes,13,opt,name=fileGetInfo,proto3,oneof"`
}

type Response_TransactionGetReceipt struct {
	TransactionGetReceipt *TransactionGetReceiptResponse `protobuf:"bytes,14,opt,name=transactionGetReceipt,proto3,oneof"`
}

type Response_TransactionGetRecord struct {
	TransactionGetRecord *TransactionGetRecordResponse `protobuf:"bytes,15,opt,name=transactionGetRecord,proto3,oneof"`
}

type Response_TransactionGetFastRecord struct {
	TransactionGetFastRecord *TransactionGetFastRecordResponse `protobuf:"bytes,16,opt,name=transactionGetFastRecord,proto3,oneof"`
}

func (*Response_GetByKey) isResponse_Response() {}

func (*Response_GetBySolidityID) isResponse_Response() {}

func (*Response_ContractCallLocal) isResponse_Response() {}

func (*Response_ContractGetBytecodeResponse) isResponse_Response() {}

func (*Response_ContractGetInfo) isResponse_Response() {}

func (*Response_ContractGetRecordsResponse) isResponse_Response() {}

func (*Response_CryptogetAccountBalance) isResponse_Response() {}

func (*Response_CryptoGetAccountRecords) isResponse_Response() {}

func (*Response_CryptoGetInfo) isResponse_Response() {}

func (*Response_CryptoGetClaim) isResponse_Response() {}

func (*Response_CryptoGetProxyStakers) isResponse_Response() {}

func (*Response_FileGetContents) isResponse_Response() {}

func (*Response_FileGetInfo) isResponse_Response() {}

func (*Response_TransactionGetReceipt) isResponse_Response() {}

func (*Response_TransactionGetRecord) isResponse_Response() {}

func (*Response_TransactionGetFastRecord) isResponse_Response() {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetGetByKey() *GetByKeyResponse {
	if x, ok := m.GetResponse().(*Response_GetByKey); ok {
		return x.GetByKey
	}
	return nil
}

func (m *Response) GetGetBySolidityID() *GetBySolidityIDResponse {
	if x, ok := m.GetResponse().(*Response_GetBySolidityID); ok {
		return x.GetBySolidityID
	}
	return nil
}

func (m *Response) GetContractCallLocal() *ContractCallLocalResponse {
	if x, ok := m.GetResponse().(*Response_ContractCallLocal); ok {
		return x.ContractCallLocal
	}
	return nil
}

func (m *Response) GetContractGetBytecodeResponse() *ContractGetBytecodeResponse {
	if x, ok := m.GetResponse().(*Response_ContractGetBytecodeResponse); ok {
		return x.ContractGetBytecodeResponse
	}
	return nil
}

func (m *Response) GetContractGetInfo() *ContractGetInfoResponse {
	if x, ok := m.GetResponse().(*Response_ContractGetInfo); ok {
		return x.ContractGetInfo
	}
	return nil
}

func (m *Response) GetContractGetRecordsResponse() *ContractGetRecordsResponse {
	if x, ok := m.GetResponse().(*Response_ContractGetRecordsResponse); ok {
		return x.ContractGetRecordsResponse
	}
	return nil
}

func (m *Response) GetCryptogetAccountBalance() *CryptoGetAccountBalanceResponse {
	if x, ok := m.GetResponse().(*Response_CryptogetAccountBalance); ok {
		return x.CryptogetAccountBalance
	}
	return nil
}

func (m *Response) GetCryptoGetAccountRecords() *CryptoGetAccountRecordsResponse {
	if x, ok := m.GetResponse().(*Response_CryptoGetAccountRecords); ok {
		return x.CryptoGetAccountRecords
	}
	return nil
}

func (m *Response) GetCryptoGetInfo() *CryptoGetInfoResponse {
	if x, ok := m.GetResponse().(*Response_CryptoGetInfo); ok {
		return x.CryptoGetInfo
	}
	return nil
}

func (m *Response) GetCryptoGetClaim() *CryptoGetClaimResponse {
	if x, ok := m.GetResponse().(*Response_CryptoGetClaim); ok {
		return x.CryptoGetClaim
	}
	return nil
}

func (m *Response) GetCryptoGetProxyStakers() *CryptoGetStakersResponse {
	if x, ok := m.GetResponse().(*Response_CryptoGetProxyStakers); ok {
		return x.CryptoGetProxyStakers
	}
	return nil
}

func (m *Response) GetFileGetContents() *FileGetContentsResponse {
	if x, ok := m.GetResponse().(*Response_FileGetContents); ok {
		return x.FileGetContents
	}
	return nil
}

func (m *Response) GetFileGetInfo() *FileGetInfoResponse {
	if x, ok := m.GetResponse().(*Response_FileGetInfo); ok {
		return x.FileGetInfo
	}
	return nil
}

func (m *Response) GetTransactionGetReceipt() *TransactionGetReceiptResponse {
	if x, ok := m.GetResponse().(*Response_TransactionGetReceipt); ok {
		return x.TransactionGetReceipt
	}
	return nil
}

func (m *Response) GetTransactionGetRecord() *TransactionGetRecordResponse {
	if x, ok := m.GetResponse().(*Response_TransactionGetRecord); ok {
		return x.TransactionGetRecord
	}
	return nil
}

func (m *Response) GetTransactionGetFastRecord() *TransactionGetFastRecordResponse {
	if x, ok := m.GetResponse().(*Response_TransactionGetFastRecord); ok {
		return x.TransactionGetFastRecord
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_GetByKey)(nil),
		(*Response_GetBySolidityID)(nil),
		(*Response_ContractCallLocal)(nil),
		(*Response_ContractGetBytecodeResponse)(nil),
		(*Response_ContractGetInfo)(nil),
		(*Response_ContractGetRecordsResponse)(nil),
		(*Response_CryptogetAccountBalance)(nil),
		(*Response_CryptoGetAccountRecords)(nil),
		(*Response_CryptoGetInfo)(nil),
		(*Response_CryptoGetClaim)(nil),
		(*Response_CryptoGetProxyStakers)(nil),
		(*Response_FileGetContents)(nil),
		(*Response_FileGetInfo)(nil),
		(*Response_TransactionGetReceipt)(nil),
		(*Response_TransactionGetRecord)(nil),
		(*Response_TransactionGetFastRecord)(nil),
	}
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("Response.proto", fileDescriptor_2c4c7055b2f7bc3f) }

var fileDescriptor_2c4c7055b2f7bc3f = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x5b, 0x60, 0xa3, 0x5c, 0x59, 0xc7, 0xcc, 0x4a, 0x4d, 0xc6, 0xca, 0x18, 0x08, 0x78,
	0xea, 0x03, 0x88, 0x57, 0x24, 0xda, 0x69, 0xed, 0x80, 0x87, 0x2a, 0x43, 0x42, 0x48, 0xbc, 0x78,
	0x8e, 0xdb, 0x46, 0x64, 0x71, 0xe4, 0x18, 0x89, 0x7c, 0x5b, 0x3e, 0xca, 0x54, 0xd7, 0x49, 0x6d,
	0xc7, 0xe9, 0x53, 0xdb, 0xfb, 0xdf, 0xff, 0x77, 0xb5, 0x7d, 0x77, 0xd0, 0x0b, 0x59, 0x9e, 0xf1,
	0x34, 0x67, 0xa3, 0x4c, 0x70, 0xc9, 0xd1, 0x9e, 0xfa, 0x08, 0x7a, 0x53, 0x26, 0xc7, 0xc5, 0x37,
	0x56, 0x6c, 0xc2, 0x41, 0x5f, 0xfd, 0xbe, 0xe6, 0x49, 0x1c, 0xc5, 0xb2, 0xb8, 0xba, 0xd0, 0xe1,
	0xc1, 0x84, 0xa7, 0x52, 0x10, 0x2a, 0x27, 0x24, 0x49, 0xbe, 0x73, 0x4a, 0x12, 0x2d, 0x3c, 0x2f,
	0x05, 0xe5, 0x93, 0x8c, 0xf2, 0x88, 0x95, 0x28, 0x43, 0xba, 0x4a, 0x17, 0x5c, 0x87, 0xb1, 0x11,
	0x0e, 0x19, 0xe5, 0x22, 0xca, 0xb5, 0x72, 0x3a, 0x11, 0x45, 0x26, 0xf9, 0x94, 0xc9, 0x2f, 0x94,
	0xf2, 0xbf, 0xa9, 0x1c, 0x93, 0x84, 0xa4, 0x94, 0x35, 0xc9, 0xb6, 0xfb, 0x69, 0x25, 0x1b, 0xc5,
	0x8e, 0xab, 0xe0, 0x24, 0x21, 0xf1, 0xad, 0x8e, 0x3e, 0xab, 0xa2, 0xd7, 0x92, 0xfc, 0x61, 0xa2,
	0x44, 0xf4, 0x2f, 0xe3, 0x84, 0xad, 0x73, 0x79, 0x2a, 0x59, 0x2a, 0xcb, 0xf0, 0x91, 0x0e, 0x1b,
	0xdc, 0x93, 0x1f, 0x82, 0xa4, 0x39, 0xa1, 0x32, 0xe6, 0xe9, 0xe6, 0x1c, 0x2c, 0xce, 0xa4, 0x16,
	0x83, 0x9a, 0xc8, 0x45, 0xa4, 0xb5, 0xa1, 0xad, 0x5d, 0x92, 0xdc, 0xd2, 0xcf, 0xff, 0x03, 0x74,
	0xca, 0x97, 0x42, 0x9f, 0xa0, 0xb3, 0xd4, 0xcf, 0x83, 0xdb, 0x67, 0xed, 0xf7, 0xdd, 0x0f, 0x83,
	0x4d, 0xda, 0xa8, 0x7c, 0xb5, 0x32, 0x75, 0xd6, 0x0a, 0xab, 0x54, 0xf4, 0x15, 0x0e, 0x97, 0xf6,
	0x2b, 0xe2, 0x7b, 0xca, 0x3d, 0x34, 0xdd, 0x5b, 0xd5, 0x80, 0xb8, 0x46, 0x34, 0x87, 0x23, 0xea,
	0x3e, 0x3d, 0xbe, 0xaf, 0x68, 0x67, 0x9a, 0x56, 0x6b, 0x0d, 0x83, 0x57, 0x37, 0xa3, 0x05, 0x9c,
	0xd0, 0x7a, 0xcf, 0x94, 0x1e, 0xbc, 0xa7, 0xd8, 0xe7, 0x0e, 0xdb, 0x93, 0x39, 0x6b, 0x85, 0xbb,
	0x40, 0xeb, 0x5b, 0xa0, 0x76, 0x03, 0xe2, 0x07, 0xd6, 0x2d, 0x38, 0xed, 0x69, 0xde, 0x82, 0x63,
	0x44, 0x14, 0x02, 0x5a, 0xeb, 0xda, 0xea, 0x2f, 0xef, 0x2b, 0xec, 0xab, 0x3a, 0xd6, 0x49, 0x9c,
	0xb5, 0xc2, 0x1d, 0x18, 0x74, 0x03, 0x03, 0xaa, 0xfa, 0x72, 0xe9, 0x0e, 0x00, 0x7e, 0xa8, 0x2a,
	0xbc, 0x2d, 0x2b, 0xf8, 0xc7, 0xc4, 0x28, 0xd3, 0x04, 0xda, 0xd6, 0xa8, 0x4d, 0x11, 0xee, 0xec,
	0xac, 0x51, 0x3f, 0x4a, 0x13, 0x08, 0x5d, 0xc0, 0x01, 0x35, 0x47, 0x11, 0x3f, 0x52, 0xe4, 0x17,
	0x2e, 0xd9, 0xb9, 0x74, 0xdb, 0x84, 0xa6, 0xd0, 0xa3, 0xd6, 0xec, 0x62, 0x50, 0x98, 0x53, 0x17,
	0xa3, 0x44, 0x83, 0xe3, 0xd8, 0xd0, 0x4f, 0xe8, 0x57, 0x91, 0xb9, 0xe0, 0xff, 0x0a, 0x3d, 0xf3,
	0xb8, 0xab, 0x78, 0x2f, 0x5d, 0x9e, 0x96, 0x0d, 0xa2, 0xdf, 0xbf, 0x6e, 0xb0, 0x85, 0xbd, 0x2f,
	0xf0, 0x63, 0xab, 0xc1, 0x9c, 0x6d, 0x62, 0x36, 0x98, 0x63, 0x44, 0x9f, 0xa1, 0xbb, 0xd8, 0x2e,
	0x19, 0x7c, 0xa0, 0x38, 0x81, 0xcd, 0x71, 0xee, 0xcb, 0x34, 0xa0, 0xdf, 0xd0, 0x97, 0xbe, 0x8d,
	0x84, 0x7b, 0x8a, 0xf4, 0x46, 0x93, 0xbc, 0x5b, 0xcb, 0x3c, 0xa9, 0x17, 0x82, 0x7e, 0xc1, 0xb1,
	0xf4, 0xac, 0x34, 0x7c, 0xa8, 0xe0, 0xaf, 0x9b, 0xe0, 0x5c, 0x44, 0x06, 0xdb, 0x8b, 0x40, 0x0c,
	0xb0, 0x6c, 0xd8, 0x88, 0xf8, 0x89, 0xc2, 0xbf, 0xf3, 0xe2, 0xb7, 0x69, 0x46, 0x89, 0x46, 0xd4,
	0x18, 0xa0, 0x23, 0x74, 0xde, 0x78, 0xb8, 0x1e, 0xe6, 0xdb, 0xd1, 0x8a, 0x45, 0x4c, 0x90, 0xd1,
	0x8a, 0xe4, 0xab, 0xa5, 0x20, 0xd9, 0x6a, 0x53, 0x66, 0xde, 0xbe, 0xd9, 0x57, 0x5f, 0x3e, 0xde,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x8b, 0x7f, 0x37, 0x32, 0x07, 0x00, 0x00,
}
