// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TransactionRecord.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Response when the client sends the node TransactionGetRecordResponse
type TransactionRecord struct {
	Receipt            *TransactionReceipt `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	TransactionHash    []byte              `protobuf:"bytes,2,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	ConsensusTimestamp *Timestamp          `protobuf:"bytes,3,opt,name=consensusTimestamp,proto3" json:"consensusTimestamp,omitempty"`
	TransactionID      *TransactionID      `protobuf:"bytes,4,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Memo               string              `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	TransactionFee     uint64              `protobuf:"varint,6,opt,name=transactionFee,proto3" json:"transactionFee,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*TransactionRecord_ContractCallResult
	//	*TransactionRecord_ContractCreateResult
	Body                 isTransactionRecord_Body `protobuf_oneof:"body"`
	TransferList         *TransferList            `protobuf:"bytes,10,opt,name=transferList,proto3" json:"transferList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TransactionRecord) Reset()         { *m = TransactionRecord{} }
func (m *TransactionRecord) String() string { return proto.CompactTextString(m) }
func (*TransactionRecord) ProtoMessage()    {}
func (*TransactionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_116f8900556a83d9, []int{0}
}

func (m *TransactionRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRecord.Unmarshal(m, b)
}
func (m *TransactionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRecord.Marshal(b, m, deterministic)
}
func (m *TransactionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRecord.Merge(m, src)
}
func (m *TransactionRecord) XXX_Size() int {
	return xxx_messageInfo_TransactionRecord.Size(m)
}
func (m *TransactionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRecord proto.InternalMessageInfo

func (m *TransactionRecord) GetReceipt() *TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionRecord) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TransactionRecord) GetConsensusTimestamp() *Timestamp {
	if m != nil {
		return m.ConsensusTimestamp
	}
	return nil
}

func (m *TransactionRecord) GetTransactionID() *TransactionID {
	if m != nil {
		return m.TransactionID
	}
	return nil
}

func (m *TransactionRecord) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *TransactionRecord) GetTransactionFee() uint64 {
	if m != nil {
		return m.TransactionFee
	}
	return 0
}

type isTransactionRecord_Body interface {
	isTransactionRecord_Body()
}

type TransactionRecord_ContractCallResult struct {
	ContractCallResult *ContractFunctionResult `protobuf:"bytes,7,opt,name=contractCallResult,proto3,oneof"`
}

type TransactionRecord_ContractCreateResult struct {
	ContractCreateResult *ContractFunctionResult `protobuf:"bytes,8,opt,name=contractCreateResult,proto3,oneof"`
}

func (*TransactionRecord_ContractCallResult) isTransactionRecord_Body() {}

func (*TransactionRecord_ContractCreateResult) isTransactionRecord_Body() {}

func (m *TransactionRecord) GetBody() isTransactionRecord_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *TransactionRecord) GetContractCallResult() *ContractFunctionResult {
	if x, ok := m.GetBody().(*TransactionRecord_ContractCallResult); ok {
		return x.ContractCallResult
	}
	return nil
}

func (m *TransactionRecord) GetContractCreateResult() *ContractFunctionResult {
	if x, ok := m.GetBody().(*TransactionRecord_ContractCreateResult); ok {
		return x.ContractCreateResult
	}
	return nil
}

func (m *TransactionRecord) GetTransferList() *TransferList {
	if m != nil {
		return m.TransferList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransactionRecord) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransactionRecord_ContractCallResult)(nil),
		(*TransactionRecord_ContractCreateResult)(nil),
	}
}

func init() {
	proto.RegisterType((*TransactionRecord)(nil), "proto.TransactionRecord")
}

func init() { proto.RegisterFile("TransactionRecord.proto", fileDescriptor_116f8900556a83d9) }

var fileDescriptor_116f8900556a83d9 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0xfc, 0xf5, 0x67, 0x01, 0x7d, 0xa2, 0xe0, 0x4a, 0xc2, 0x4a, 0xa2, 0x69, 0x3c, 0x98, 0x9e,
	0x7a, 0x90, 0x83, 0x89, 0x27, 0x03, 0x84, 0x40, 0x42, 0xa2, 0x59, 0xf9, 0x02, 0xcb, 0xf2, 0xb4,
	0x4d, 0xda, 0x6e, 0xb3, 0xbb, 0x1c, 0xf8, 0x1c, 0x7e, 0x61, 0xe3, 0x76, 0x8b, 0xfc, 0x3b, 0x78,
	0xea, 0xcb, 0xcc, 0xbc, 0x99, 0xd7, 0x59, 0xe8, 0xce, 0x15, 0xcf, 0x35, 0x17, 0x26, 0x91, 0x39,
	0x43, 0x21, 0xd5, 0x32, 0x2a, 0x94, 0x34, 0x92, 0xd4, 0xec, 0xa7, 0xd7, 0x9a, 0x27, 0x19, 0x6a,
	0xc3, 0xb3, 0xa2, 0xc4, 0x7b, 0xed, 0x01, 0xd7, 0x89, 0x98, 0xaf, 0x0b, 0xd4, 0x0e, 0xa1, 0xbb,
	0x16, 0x98, 0x14, 0xc6, 0x31, 0x9d, 0xa1, 0x5a, 0x17, 0x46, 0x5a, 0xfe, 0x03, 0x95, 0x43, 0xbb,
	0x43, 0x99, 0x1b, 0xc5, 0x85, 0x19, 0xf2, 0x34, 0x9d, 0x49, 0xc1, 0xd3, 0x92, 0xb8, 0xff, 0xf2,
	0xe1, 0xea, 0xe0, 0x1c, 0xd2, 0x87, 0x86, 0x2a, 0x5d, 0xa9, 0x17, 0x78, 0xe1, 0xf9, 0xe3, 0x4d,
	0x29, 0x8f, 0x0e, 0x63, 0x59, 0xa5, 0x24, 0x21, 0xb4, 0xcc, 0x2f, 0x3d, 0xe1, 0x3a, 0xa6, 0xff,
	0x03, 0x2f, 0x6c, 0xb2, 0x7d, 0x98, 0xbc, 0x00, 0x11, 0x32, 0xd7, 0x98, 0xeb, 0x95, 0xde, 0xfc,
	0x2b, 0x3d, 0xb1, 0x49, 0xed, 0x2a, 0xa9, 0xc2, 0xd9, 0x11, 0x2d, 0x79, 0x86, 0x8b, 0x2d, 0xd3,
	0xe9, 0x88, 0xfa, 0x76, 0xb9, 0x73, 0x78, 0xe6, 0x74, 0xc4, 0x76, 0xa5, 0x84, 0x80, 0x9f, 0x61,
	0x26, 0x69, 0x2d, 0xf0, 0xc2, 0x33, 0x66, 0x67, 0xf2, 0x00, 0x97, 0x5b, 0xa2, 0x31, 0x22, 0xad,
	0x07, 0x5e, 0xe8, 0xb3, 0x3d, 0x94, 0xbc, 0xda, 0xcb, 0x37, 0x4d, 0x32, 0xd4, 0xab, 0xd4, 0xd0,
	0x86, 0x0d, 0xbf, 0x75, 0xe1, 0x55, 0xd5, 0xe3, 0x55, 0xee, 0x8a, 0xfa, 0x11, 0x4d, 0xfe, 0xb1,
	0x23, 0xab, 0xe4, 0x1d, 0x3a, 0x1b, 0x54, 0x21, 0x37, 0xe8, 0x2c, 0x4f, 0xff, 0x66, 0x79, 0x74,
	0x99, 0x3c, 0x41, 0xd3, 0xb8, 0xf7, 0x9f, 0x25, 0xda, 0x50, 0xb0, 0x66, 0xd7, 0xdb, 0xe5, 0x38,
	0x8a, 0xed, 0x08, 0x07, 0x75, 0xf0, 0x17, 0x72, 0xb9, 0x1e, 0xdc, 0x41, 0x4f, 0xc8, 0x2c, 0x8a,
	0x71, 0x89, 0x8a, 0x47, 0x31, 0xd7, 0xf1, 0xa7, 0xe2, 0x45, 0x5c, 0x1a, 0xbc, 0x79, 0x8b, 0xba,
	0x1d, 0xfa, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0x33, 0x34, 0xb5, 0xca, 0x02, 0x00, 0x00,
}
