name: GitHub Pages

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
    
jobs:
    publish:
        name: Update GitHub Pages
        if: success()
        runs-on: ubuntu-latest
        env:
            HEDERA_NETWORK: localhost
            OPERATOR_ID: ${{ secrets.LOCAL_OPERATOR_ID }}
            OPERATOR_KEY: ${{ secrets.LOCAL_OPERATOR_KEY }}
            GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

        steps:
            - name: Set up Go 1.19
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v3

            - name: Install gopages
              run: go install github.com/johnstarich/go/gopages@latest
            - name: Print PAT value
              run: echo $GH_PAGES_TOKEN

            - name: Deploy to GitHub Pages
              run: gopages -gh-pages -gh-pages-token $GH_PAGES_TOKEN

