name: Hedera Services Main

defaults:
    run:
        shell: bash

permissions:
    contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: [ self-hosted, Linux, medium, ephemeral ]
    strategy:
      matrix:
        version: [ 'current', 'latest' ]

    steps:
      -   name: Harden Runner
          uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
          with:
            egress-policy: audit

      -   name: Setup NodeJS
          uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
          with:
            node-version: 18

      # Set up Gradle with Caching Enabled
      -   name: Setup Gradle
          uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # v3.3.2

      -   name: Setup Java
          uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
          with:
            distribution: temurin
            java-version: 17

      -   name: Setup GCC
          run: |
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      -   name: Set up Go 1.20
          uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
          with:
            go-version: "1.20"
          id: go

      - name: Fetch Hedera Services
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          repository: hashgraph/hedera-services
          path: hedera-services

      -   name: Fetch Hedera SDK
          uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
          with:
              path: hedera-sdk-go

      - name: Get Current Tag
        working-directory: hedera-services
        if: ${{ matrix.version == 'current' }}
        run: |
          git tag MASTER
          echo "TAG=MASTER" >> .env
          echo "TAG=MASTER" >> $GITHUB_ENV

      - name: Get Latest Tag
        if: ${{ matrix.version == 'latest' }}
        working-directory: hedera-services
        run: |
          git fetch --unshallow --tags
          export TAG=$(git log --tags --simplify-by-decoration --pretty="format:%d" | grep "^\s(tag:\sv[0-9]\+\.[0-9]\+\.[0-9]\+\(-[A-Za-z0-9]\+\(\.[0-9]\+\)\?\)\?)\$" | head -n 1 | sed -e "s#\s(tag:\s\(.*\))#\1#g")
          echo "TAG=$TAG" > .env
          echo "TAG=$TAG" > $GITHUB_ENV

      - name: Build Hedera Services
        working-directory: hedera-services
        run: docker build -t services-node:$TAG .

      - name: Run Hedera SDK Tests
        env:
          OPERATOR_KEY: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
          OPERATOR_ID: "0.0.2"
          HEDERA_NETWORK: "localhost"
        run: |
          cd hedera-services
          docker-compose up &
          cd ../hedera-sdk-go
          go test -tags="e2e" -coverprofile=coverage.out -covermode=atomic -v -timeout 9999s
      - uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
