name: Hedera Services Main

defaults:
    run:
        shell: bash

permissions:
    contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: [ self-hosted, Linux, medium, ephemeral ]
    strategy:
      matrix:
        version: [ 'current', 'latest' ]

    steps:
      -   name: Harden Runner
          uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
          with:
            egress-policy: audit

      -   name: Setup NodeJS
          uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
          with:
            node-version: 18

      # Set up Gradle with Caching Enabled
      -   name: Setup Gradle
          uses: gradle/gradle-build-action@66535aaf56f831b35e3a8481c9c99b665b84dd45 # v3.4.2

      -   name: Setup Java
          uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
          with:
            distribution: temurin
            java-version: 17

      -   name: Setup GCC
          run: |
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      -   name: Set up Go 1.20
          uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
          with:
            go-version: "1.20"
          id: go

      - name: Fetch Hedera Services
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: hashgraph/hedera-services
          path: hedera-services

      -   name: Fetch Hedera SDK
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
              path: hedera-sdk-go

      - name: Get Current Tag
        working-directory: hedera-services
        if: ${{ matrix.version == 'current' }}
        run: |
          git tag MASTER
          echo "TAG=MASTER" >> .env
          echo "TAG=MASTER" >> $GITHUB_ENV

      - name: Get Latest Tag
        if: ${{ matrix.version == 'latest' }}
        working-directory: hedera-services
        run: |
          git fetch --unshallow --tags
          export TAG=$(git log --tags --simplify-by-decoration --pretty="format:%d" | grep "^\s(tag:\sv[0-9]\+\.[0-9]\+\.[0-9]\+\(-[A-Za-z0-9]\+\(\.[0-9]\+\)\?\)\?)\$" | head -n 1 | sed -e "s#\s(tag:\s\(.*\))#\1#g")
          echo "TAG=$TAG" > .env
          echo "TAG=$TAG" > $GITHUB_ENV

      - name: Build Hedera Services
        working-directory: hedera-services
        run: docker build -t services-node:$TAG .

      - name: Run Hedera SDK Tests
        env:
          OPERATOR_KEY: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
          OPERATOR_ID: "0.0.2"
          HEDERA_NETWORK: "localhost"
        run: |
          cd hedera-services
          docker-compose up &
          cd ../hedera-sdk-go
          go test -tags="e2e" -coverprofile=coverage.out -covermode=atomic -v -timeout 9999s
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
