name: Hedera Services Main

defaults:
    run:
        shell: bash

permissions:
    contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: [ self-hosted, Linux, medium, ephemeral ]
    strategy:
      matrix:
        version: [ 'current', 'latest' ]

    steps:
      -   name: Setup NodeJS
          uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
          with:
            node-version: 18

      # Set up Gradle with Caching Enabled
      -   name: Setup Gradle
          uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3.1.0

      -   name: Setup Java
          uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
          with:
            distribution: temurin
            java-version: 17

      -   name: Setup GCC
          run: |
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      -   name: Set up Go 1.19
          uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
          with:
            go-version: 1.19
          id: go

      - name: Fetch Hedera Services
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: hashgraph/hedera-services
          path: hedera-services

      -   name: Fetch Hedera SDK
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          with:
              path: hedera-sdk-go

      - name: Get Current Tag
        working-directory: hedera-services
        if: ${{ matrix.version == 'current' }}
        run: |
          git tag MASTER
          echo "TAG=MASTER" >> .env
          echo "TAG=MASTER" >> $GITHUB_ENV

      - name: Get Latest Tag
        if: ${{ matrix.version == 'latest' }}
        working-directory: hedera-services
        run: |
          git fetch --unshallow --tags
          export TAG=$(git log --tags --simplify-by-decoration --pretty="format:%d" | grep "^\s(tag:\sv[0-9]\+\.[0-9]\+\.[0-9]\+\(-[A-Za-z0-9]\+\(\.[0-9]\+\)\?\)\?)\$" | head -n 1 | sed -e "s#\s(tag:\s\(.*\))#\1#g")
          echo "TAG=$TAG" > .env
          echo "TAG=$TAG" > $GITHUB_ENV

      - name: Build Hedera Services
        working-directory: hedera-services
        run: docker build -t services-node:$TAG .

      - name: Run Hedera SDK Tests
        env:
          OPERATOR_KEY: ${{ secrets.LOCAL_OPERATOR_KEY }}
          OPERATOR_ID: ${{ secrets.LOCAL_OPERATOR_ID }}
          HEDERA_NETWORK: "localhost"
        run: |
          cd hedera-services
          docker-compose up &
          cd ../hedera-sdk-go
          go test -tags="e2e" -coverprofile=coverage.out -covermode=atomic -v -timeout 9999s
      - uses: codecov/codecov-action@7afa10ed9b269c561c2336fd862446844e0cbf71 # v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
