name: Testnet
env:
    OPERATOR_KEY: ${{ secrets.TESTNET_OPERATOR_KEY }}
    OPERATOR_ID: ${{ secrets.TESTNET_OPERATOR_ID }}
    HEDERA_NETWORK: "testnet"

defaults:
    run:
        shell: bash

permissions:
    contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: hiero-client-sdk-linux-medium
    steps:
      -   name: Harden Runner
          uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
          with:
            egress-policy: audit

      -   name: Setup GCC
          run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      - name: Set up Go 1.20
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Vet Examples
        run: go vet ./examples/...

      - name: Vet
        run: go vet .

      - name: Build
        run: go build -v .

  test:
    name: Test
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Setup GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc libc6-dev libc-dev

      - name: Set up Go 1.19
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: go test -v -timeout 9999s

  golangci:
    name: lint
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v1.50
