name: CI against testnet
env:
    OPERATOR_KEY: ${{ secrets.TESTNET_OPERATOR_KEY }}
    OPERATOR_ID: ${{ secrets.TESTNET_OPERATOR_ID }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Vet Examples
        run: go vet ./examples/...

      - name: Vet
        run: go vet .

      - name: Lint
        run: if [[ $(gofmt -l ./) ]]; then false; else true; fi

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v -timeout 9999s
