name: CI against testnet
env:
    OPERATOR_KEY: ${{ secrets.TESTNET_OPERATOR_KEY }}
    OPERATOR_ID: ${{ secrets.TESTNET_OPERATOR_ID }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Vet Examples
        run: go vet ./examples/...

      - name: Vet
        run: go vet .

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v -timeout 9999s
